spring.datasource.url=jdbc:mysql://localhost:3306/biography_db
spring.datasource.username=root
spring.datasource.password=biography

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.username=xinghuoji.ai@gmail.com
spring.mail.password=qscs kgyl fjwj mfzm

# spring.mail.host=smtp.yunyou.top
# spring.mail.port=587

# spring.mail.username=xinghuoji@dadiorg.com
# spring.mail.password=DAdi#20260624
# SMTP_HOST=smtp.yunyou.top
# SMTP_PORT=587
# SMTP_USERNAME=xinghuoji@dadiorg.com
# SMTP_PASSWORD=DAdi#20260624
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
# spring.mail.properties.mail.smtp.ssl.enable=false

app.frontend.url=http://localhost:3000