spring.datasource.url=jdbc:mysql://localhost:3306/biography_db
spring.datasource.username=root
spring.datasource.password=biography

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true