-- ============================================================
-- AI Autobiography - Membership and Payment Schema
-- MySQL 8+
-- ============================================================


-- ============================================================
-- 1. MEMBERSHIP PLANS
-- Defines the membership product being offered.
-- Example: DIY Membership = RMB 360 / 12 months
-- ============================================================

CREATE TABLE membership_plans (
    plan_id CHAR(36) NOT NULL,

    name VARCHAR(100) NOT NULL,

    standard_price DECIMAL(10, 2) NOT NULL,

    currency VARCHAR(10) NOT NULL DEFAULT 'CNY',

    duration_months INT NOT NULL,

    refund_window_days INT NOT NULL DEFAULT 7,

    is_active TINYINT(1) NOT NULL DEFAULT 1,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (plan_id),

    CONSTRAINT chk_membership_plan_price
        CHECK (standard_price >= 0),

    CONSTRAINT chk_membership_plan_duration
        CHECK (duration_months > 0),

    CONSTRAINT chk_membership_plan_refund_window
        CHECK (refund_window_days >= 0)
);


-- ============================================================
-- 2. MEMBERSHIPS
-- Membership belongs to the USER, not to a specific website.
--
-- A user may therefore publish multiple biography websites
-- while their membership is active.
--
-- Multiple membership records are allowed to preserve history.
-- ============================================================

CREATE TABLE memberships (
    membership_id CHAR(36) NOT NULL,

    user_id CHAR(36) NOT NULL,

    plan_id CHAR(36) NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    start_at DATETIME NULL,

    expires_at DATETIME NULL,

    auto_renew TINYINT(1) NOT NULL DEFAULT 1,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (membership_id),

    CONSTRAINT fk_memberships_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_memberships_plan
        FOREIGN KEY (plan_id)
        REFERENCES membership_plans(plan_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    INDEX idx_memberships_user_id (user_id),

    INDEX idx_memberships_plan_id (plan_id),

    INDEX idx_memberships_status (status),

    INDEX idx_memberships_user_status (user_id, status)
);


-- ============================================================
-- 3. PAYMENTS
-- Supports the current manual payment verification process.
--
-- payment_reference:
--     Reference generated by our application.
--
-- payment_remark:
--     Username / identifying information associated with
--     the manual WeChat payment.
--
-- verified_by:
--     Admin/user who manually verified the payment.
-- ============================================================

CREATE TABLE payments (
    payment_id CHAR(36) NOT NULL,

    membership_id CHAR(36) NOT NULL,

    user_id CHAR(36) NOT NULL,

    payment_reference VARCHAR(100) NOT NULL,

    amount DECIMAL(10, 2) NOT NULL,

    currency VARCHAR(10) NOT NULL DEFAULT 'CNY',

    payment_method VARCHAR(30) NOT NULL,

    payment_remark VARCHAR(255) NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    paid_at DATETIME NULL,

    verified_by CHAR(36) NULL,

    verified_at DATETIME NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (payment_id),

    CONSTRAINT uq_payments_reference
        UNIQUE (payment_reference),

    CONSTRAINT fk_payments_membership
        FOREIGN KEY (membership_id)
        REFERENCES memberships(membership_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_payments_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_payments_verified_by
        FOREIGN KEY (verified_by)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_payments_amount
        CHECK (amount >= 0),

    INDEX idx_payments_membership_id (membership_id),

    INDEX idx_payments_user_id (user_id),

    INDEX idx_payments_status (status),

    INDEX idx_payments_created_at (created_at),

    INDEX idx_payments_user_status (user_id, status)
);


-- ============================================================
-- 4. REFUNDS
-- One payment can have zero or one refund.
--
-- Refund eligibility is NOT stored as a boolean.
-- Backend should calculate:
--
-- payment.paid_at + membership_plan.refund_window_days
--
-- Current business rule: full refund within 7 days.
-- ============================================================

CREATE TABLE refunds (
    refund_id CHAR(36) NOT NULL,

    payment_id CHAR(36) NOT NULL,

    amount DECIMAL(10, 2) NOT NULL,

    currency VARCHAR(10) NOT NULL DEFAULT 'CNY',

    reason VARCHAR(500) NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',

    refund_method VARCHAR(30) NULL,

    external_refund_reference VARCHAR(255) NULL,

    requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    processed_at DATETIME NULL,

    processed_by CHAR(36) NULL,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (refund_id),

    -- Enforces:
    -- one payment -> maximum one refund
    CONSTRAINT uq_refunds_payment_id
        UNIQUE (payment_id),

    CONSTRAINT fk_refunds_payment
        FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_refunds_processed_by
        FOREIGN KEY (processed_by)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_refunds_amount
        CHECK (amount >= 0),

    INDEX idx_refunds_status (status),

    INDEX idx_refunds_requested_at (requested_at)
);