-- =========================================================
-- Biography Template Editable Sections
-- MySQL 8+ / Flyway
--
-- Assumption:
-- biography_websites.website_id is CHAR(36)
--
-- UUID values should be generated by Spring Boot.
-- =========================================================


-- =========================================================
-- 1. SHARED MEDIA ASSETS
-- Stores images and videos used by different sections.
-- =========================================================

CREATE TABLE website_media_assets (
    media_asset_id CHAR(36) NOT NULL,
    website_id CHAR(36) NOT NULL,

    media_type VARCHAR(30) NOT NULL,
    original_file_name VARCHAR(500),
    storage_key VARCHAR(1000) NOT NULL,
    public_url VARCHAR(2000),

    mime_type VARCHAR(150),
    file_size_bytes BIGINT,
    width_px INT,
    height_px INT,
    duration_seconds INT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (media_asset_id),

    CONSTRAINT fk_media_asset_website
        FOREIGN KEY (website_id)
        REFERENCES biography_websites (website_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_media_asset_type
        CHECK (
            media_type IN (
                'IMAGE',
                'VIDEO',
                'AUDIO',
                'DOCUMENT'
            )
        )
);

CREATE INDEX idx_media_asset_website
    ON website_media_assets (website_id);


-- =========================================================
-- 2. GENERIC WEBSITE SECTIONS
-- Every editable section has one record in this table.
-- =========================================================

CREATE TABLE biography_sections (
    section_id CHAR(36) NOT NULL,
    website_id CHAR(36) NOT NULL,

    section_type VARCHAR(50) NOT NULL,
    section_key VARCHAR(100) NOT NULL,

    sort_order INT NOT NULL DEFAULT 0,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (section_id),

    CONSTRAINT fk_biography_section_website
        FOREIGN KEY (website_id)
        REFERENCES biography_websites (website_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_website_section_key
        UNIQUE (website_id, section_key),

    CONSTRAINT chk_biography_section_type
        CHECK (
            section_type IN (
                'HERO',
                'CHRONICLE_VALUES',
                'SPECIALIZED_PURSUITS',
                'LIFE_JOURNEY',
                'MEDIA_GALLERY',
                'CONTACT'
            )
        )
);

CREATE INDEX idx_biography_section_website
    ON biography_sections (website_id);

CREATE INDEX idx_biography_section_order
    ON biography_sections (website_id, sort_order);


-- =========================================================
-- 3. HERO SECTION
-- One hero record per HERO biography section.
-- =========================================================

CREATE TABLE hero_sections (
    section_id CHAR(36) NOT NULL,

    full_name VARCHAR(255) NOT NULL,
    designation VARCHAR(255),
    tagline VARCHAR(500),
    short_description TEXT,

    profile_image_id CHAR(36),
    background_image_id CHAR(36),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (section_id),

    CONSTRAINT fk_hero_section
        FOREIGN KEY (section_id)
        REFERENCES biography_sections (section_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_hero_profile_image
        FOREIGN KEY (profile_image_id)
        REFERENCES website_media_assets (media_asset_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_hero_background_image
        FOREIGN KEY (background_image_id)
        REFERENCES website_media_assets (media_asset_id)
        ON DELETE SET NULL
);


-- =========================================================
-- 4. CHRONICLE AND VALUES SECTION
-- Stores section headings and the single journal block.
-- =========================================================

CREATE TABLE chronicle_sections (
    section_id CHAR(36) NOT NULL,

    section_label VARCHAR(255),
    section_title VARCHAR(255) NOT NULL,
    section_description TEXT,

    journal_card_label VARCHAR(255),
    journal_story_title VARCHAR(255),
    journal_story_content LONGTEXT,
    journal_quote TEXT,

    beliefs_card_label VARCHAR(255),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (section_id),

    CONSTRAINT fk_chronicle_section
        FOREIGN KEY (section_id)
        REFERENCES biography_sections (section_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 5. BELIEF ITEMS
-- Repeatable items under Chronicle and Values.
-- =========================================================

CREATE TABLE belief_items (
    belief_item_id CHAR(36) NOT NULL,
    section_id CHAR(36) NOT NULL,

    icon VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    description TEXT,

    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (belief_item_id),

    CONSTRAINT fk_belief_item_chronicle
        FOREIGN KEY (section_id)
        REFERENCES chronicle_sections (section_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_belief_item_section
    ON belief_items (section_id);

CREATE INDEX idx_belief_item_order
    ON belief_items (section_id, sort_order);


-- =========================================================
-- 6. SPECIALIZED PURSUITS SECTION
-- =========================================================

CREATE TABLE pursuit_sections (
    section_id CHAR(36) NOT NULL,

    section_label VARCHAR(255),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (section_id),

    CONSTRAINT fk_pursuit_section
        FOREIGN KEY (section_id)
        REFERENCES biography_sections (section_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 7. PURSUIT ITEMS
-- Repeatable cards under Specialized Pursuits.
-- =========================================================

CREATE TABLE pursuit_items (
    pursuit_item_id CHAR(36) NOT NULL,
    section_id CHAR(36) NOT NULL,

    image_id CHAR(36),
    icon VARCHAR(255),

    title VARCHAR(255) NOT NULL,
    description TEXT,

    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (pursuit_item_id),

    CONSTRAINT fk_pursuit_item_section
        FOREIGN KEY (section_id)
        REFERENCES pursuit_sections (section_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pursuit_item_image
        FOREIGN KEY (image_id)
        REFERENCES website_media_assets (media_asset_id)
        ON DELETE SET NULL
);

CREATE INDEX idx_pursuit_item_section
    ON pursuit_items (section_id);

CREATE INDEX idx_pursuit_item_order
    ON pursuit_items (section_id, sort_order);


-- =========================================================
-- 8. LIFE JOURNEY TIMELINE SECTION
-- =========================================================

CREATE TABLE timeline_sections (
    section_id CHAR(36) NOT NULL,

    section_label VARCHAR(255),
    section_title VARCHAR(255) NOT NULL,
    section_description TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (section_id),

    CONSTRAINT fk_timeline_section
        FOREIGN KEY (section_id)
        REFERENCES biography_sections (section_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 9. TIMELINE EVENTS
-- Repeatable timeline entries.
-- =========================================================

CREATE TABLE timeline_events (
    timeline_event_id CHAR(36) NOT NULL,
    section_id CHAR(36) NOT NULL,

    time_period VARCHAR(100),
    title VARCHAR(255) NOT NULL,
    location VARCHAR(500),
    quote TEXT,

    image_id CHAR(36),
    image_alt_text VARCHAR(500),
    image_caption TEXT,

    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (timeline_event_id),

    CONSTRAINT fk_timeline_event_section
        FOREIGN KEY (section_id)
        REFERENCES timeline_sections (section_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_timeline_event_image
        FOREIGN KEY (image_id)
        REFERENCES website_media_assets (media_asset_id)
        ON DELETE SET NULL
);

CREATE INDEX idx_timeline_event_section
    ON timeline_events (section_id);

CREATE INDEX idx_timeline_event_order
    ON timeline_events (section_id, sort_order);


-- =========================================================
-- 10. TIMELINE HIGHLIGHTS
-- Repeatable bullet points under each timeline event.
-- =========================================================

CREATE TABLE timeline_highlights (
    timeline_highlight_id CHAR(36) NOT NULL,
    timeline_event_id CHAR(36) NOT NULL,

    highlight_text TEXT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (timeline_highlight_id),

    CONSTRAINT fk_timeline_highlight_event
        FOREIGN KEY (timeline_event_id)
        REFERENCES timeline_events (timeline_event_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_timeline_highlight_event
    ON timeline_highlights (timeline_event_id);

CREATE INDEX idx_timeline_highlight_order
    ON timeline_highlights (
        timeline_event_id,
        sort_order
    );


-- =========================================================
-- 11. MEDIA GALLERY SECTION
-- =========================================================

CREATE TABLE gallery_sections (
    section_id CHAR(36) NOT NULL,

    section_label VARCHAR(255),
    section_title VARCHAR(255) NOT NULL,
    section_description TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (section_id),

    CONSTRAINT fk_gallery_section
        FOREIGN KEY (section_id)
        REFERENCES biography_sections (section_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 12. GALLERY ITEMS
-- Repeatable gallery cards.
-- =========================================================

CREATE TABLE gallery_items (
    gallery_item_id CHAR(36) NOT NULL,
    section_id CHAR(36) NOT NULL,

    media_asset_id CHAR(36),
    thumbnail_asset_id CHAR(36),

    media_type VARCHAR(30) NOT NULL DEFAULT 'IMAGE',
    category VARCHAR(100),
    record_label VARCHAR(255),
    display_year VARCHAR(50),

    title VARCHAR(255) NOT NULL,
    description TEXT,
    alt_text VARCHAR(500),

    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (gallery_item_id),

    CONSTRAINT fk_gallery_item_section
        FOREIGN KEY (section_id)
        REFERENCES gallery_sections (section_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_gallery_item_media
        FOREIGN KEY (media_asset_id)
        REFERENCES website_media_assets (media_asset_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_gallery_item_thumbnail
        FOREIGN KEY (thumbnail_asset_id)
        REFERENCES website_media_assets (media_asset_id)
        ON DELETE SET NULL,

    CONSTRAINT chk_gallery_item_media_type
        CHECK (
            media_type IN (
                'IMAGE',
                'VIDEO',
                'AUDIO'
            )
        )
);

CREATE INDEX idx_gallery_item_section
    ON gallery_items (section_id);

CREATE INDEX idx_gallery_item_order
    ON gallery_items (section_id, sort_order);

CREATE INDEX idx_gallery_item_category
    ON gallery_items (section_id, category);


-- =========================================================
-- 13. CONTACT SECTION
-- =========================================================

CREATE TABLE contact_sections (
    section_id CHAR(36) NOT NULL,

    section_label VARCHAR(255),
    section_title VARCHAR(255) NOT NULL,
    section_description TEXT,

    contact_label VARCHAR(255),
    contact_email VARCHAR(320),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (section_id),

    CONSTRAINT fk_contact_section
        FOREIGN KEY (section_id)
        REFERENCES biography_sections (section_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 14. SOCIAL LINKS
-- Repeatable social-media links.
-- =========================================================

CREATE TABLE social_links (
    social_link_id CHAR(36) NOT NULL,
    section_id CHAR(36) NOT NULL,

    platform VARCHAR(100) NOT NULL,
    display_name VARCHAR(255),
    profile_url VARCHAR(2000),
    icon VARCHAR(255),

    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (social_link_id),

    CONSTRAINT fk_social_link_contact
        FOREIGN KEY (section_id)
        REFERENCES contact_sections (section_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_social_link_section
    ON social_links (section_id);

CREATE INDEX idx_social_link_order
    ON social_links (section_id, sort_order);


-- =========================================================
-- 15. CONTACT FORM SETTINGS
-- Stores editable form labels and messages.
-- =========================================================

CREATE TABLE contact_form_settings (
    section_id CHAR(36) NOT NULL,

    form_title VARCHAR(255),

    name_placeholder VARCHAR(255),
    email_placeholder VARCHAR(255),
    subject_placeholder VARCHAR(500),
    message_placeholder VARCHAR(500),

    submit_button_text VARCHAR(100),
    success_message VARCHAR(500),
    error_message VARCHAR(500),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (section_id),

    CONSTRAINT fk_contact_form_settings
        FOREIGN KEY (section_id)
        REFERENCES contact_sections (section_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 16. CONTACT MESSAGES
-- Stores messages submitted by website visitors.
-- This is user-generated data, not template content.
-- =========================================================

CREATE TABLE contact_messages (
    contact_message_id CHAR(36) NOT NULL,
    website_id CHAR(36) NOT NULL,

    sender_name VARCHAR(255) NOT NULL,
    sender_email VARCHAR(320) NOT NULL,
    subject VARCHAR(500),
    message TEXT NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'NEW',

    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP NULL,
    replied_at TIMESTAMP NULL,

    PRIMARY KEY (contact_message_id),

    CONSTRAINT fk_contact_message_website
        FOREIGN KEY (website_id)
        REFERENCES biography_websites (website_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_contact_message_status
        CHECK (
            status IN (
                'NEW',
                'READ',
                'REPLIED',
                'ARCHIVED',
                'SPAM'
            )
        )
);

CREATE INDEX idx_contact_message_website
    ON contact_messages (website_id);

CREATE INDEX idx_contact_message_status
    ON contact_messages (website_id, status);

CREATE INDEX idx_contact_message_date
    ON contact_messages (website_id, submitted_at);